name: servicec
version: 0.1.0
description: A compiler for 'service api' descriptions.
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  args: '>=0.12.2+2 <0.13.0'
  path: '>=1.3.1 <1.4.0'
  petitparser: '>=1.3.3 <2.0.0'
