name: immic
version: 0.1.0
description: A compiler for 'immi graph' descriptions.
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  args: '>=0.12.2+2 <0.13.0'
  path: '>=1.3.1 <1.4.0'
  petitparser: '>=1.3.3 <2.0.0'
  strings: '>=0.0.6 <0.0.7'
  package_config: '>=0.1.3 <0.2.0'
